export interface Product{
    id:number
    type:string
    imported:string
    description:string
    brand:string
    unit_price:number
    type_change:number
    bill_text:string
    date_bill:Date
    model:string
    origin:string
    date_manufacture:Date
    minsa_code:string
    minsa_description:string
    supplier:string
    entry_point:string
    exit_point:string
    date:Date
    entry_guide:string
    exit_guide:string
    proyect:string
    responsible:string
    coin_bill:string
    series_input:string
    selected_serie:string
    total_amount:number
    final_amount:number
    final_amount_bill:number
}